apiVersion: v2
name: bors-ng
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "latest"

# GitHub users or organisations
maintainers:
  - name: "bors-ng"

dependencies:
- name: postgresql
  condition: postgresql.enabled
  version: "11.6.0"
  repository: https://raw.githubusercontent.com/bitnami/charts/e0169502c14943782da50fc1977483fecd6912b5/bitnami
